### ISSUE TITLE
Failed to compile this project

### ISSUE THREAD

**Issue by qings2329** [ethereumproject/parity#5]
error: failed to load source for a dependency on `parity-ui-precompiled`        

Caused by:
  Unable to update https://github.com/paritytech/js-precompiled.git?branch=beta#79143dc3

Caused by:
  revspec '79143dc37fee32f2b1d7ca0805540d1de02db7a9' not found; class=Reference (4); code=NotFound (-3)

**Comment by Laziemo** [comment]
eclassic@d76:~/nodes/parity-ethereum$ RUST_BACKTRACE=1 cargo build --release --features final
   Compiling hidapi v0.3.1 (https://github.com/paritytech/hidapi-rs#d4d32376)                                                                                                                               
   Compiling idna v0.1.5                                                                                                                                                                                    
   Compiling typenum v1.10.0                                                                                                                                                                                
   Compiling crunchy v0.2.1                                                                                                                                                                                 
   Compiling xmltree v0.7.0                                                                                                                                                                                 
   Compiling winapi v0.3.6                                                                                                                                                                                  
   Compiling kernel32-sys v0.2.2                                                                                                                                                                            
   Compiling parking_lot_core v0.3.1                                                                                                                                                                        
   Compiling lazy_static v1.1.0                                                                                                                                                                             
error: failed to run custom build command for `hidapi v0.3.1 (https://github.com/paritytech/hidapi-rs#d4d32376)`                                                                                            
process didn't exit successfully: `/home/eclassic/nodes/parity-ethereum/target/release/build/hidapi-7b8e690a779853db/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-Wall" "-Wextra" "-o" "/home/eclassic/nodes/parity-ethereum/target/release/build/hidapi-783de682732e743b/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c"
cargo:warning=etc/hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
cargo:warning= #include <libudev.h>
cargo:warning=          ^~~~~~~~~~~
cargo:warning=compilation terminated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-Wall" "-Wextra" "-o" "/home/eclassic/nodes/parity-ethereum/target/release/build/hidapi-783de682732e743b/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/eclassic/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:346
   7: cc::fail
   8: cc::Build::compile
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Laziemo** [comment]
this might be because its the nightly build. compiling the latest release right now.

**Comment by Laziemo** [comment]
...yeah, doesnt build ((

eclassic@d76:~/nodes/parity-1.7.2$ RUST_BACKTRACE=1 cargo build --release --features final
    Updating git repository `https://github.com/paritytech/hyper`
    Updating git repository `https://github.com/paritytech/rust-rocksdb`                                                                                                                                    
    Updating git repository `https://github.com/paritytech/nanomsg.rs.git`                                                                                                                                  
    Updating git repository `https://github.com/paritytech/wasm-utils`                                                                                                                                      
    Updating git repository `https://github.com/paritytech/js-precompiled.git`                                                                                                                              
error: failed to load source for a dependency on `parity-ui-precompiled`                                                                                                                                    

Caused by:
  Unable to update https://github.com/paritytech/js-precompiled.git?branch=beta#79143dc3

Caused by:
  revspec '79143dc37fee32f2b1d7ca0805540d1de02db7a9' not found; class=Reference (4); code=NotFound (-3)

**Comment by Laziemo** [comment]
https://github.com/paritytech/parity-ethereum

> error: failed to load source for a dependency on `parity-ui-precompiled`
> 
> Caused by:
> Unable to update https://github.com/paritytech/js-precompiled.git?branch=beta#79143dc3
> 
> Caused by:
> revspec '79143dc37fee32f2b1d7ca0805540d1de02db7a9' not found; class=Reference (4); code=NotFound (-3)

https://github.com/paritytech/parity-ethereum

**Comment by Laziemo** [comment]
dont think this is being maintained anymore.

**Comment by i5hi** [comment]
https://github.com/paritytech/parity-ethereum

**Comment by splix** [comment]
It's recommended to use original project. This fork was only used to submit PRs to original one
